apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.environment_file }}
  namespace: {{ .Values.namespace }}
  labels:
    environment: {{ .Values.environment }}
data:
  {{- toYaml .Values.config_map.data | nindent 2 }}