---
{{- if .Values.secrets.external.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.environment}}-aws-ps-{{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.namespace }}-sa
{{- end }}
---
{{- if .Values.secrets.external.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets_name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  refreshInterval: "{{ .Values.secrets.external.refreshInterval}}"
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.environment}}-aws-ps-{{ .Values.app_name }}
  target:
    name: {{ .Values.secrets_name }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.secrets.external.data | nindent 4 }}
{{- end }}
---
{{- if .Values.secrets.internal.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets_name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets.internal.data | nindent 2 }}
{{- end }}